# 源目录
source = "../Decoherence/src"

# 目标目录
destiny = "src/Decoherence"

# 要同步的路径
sync_paths = [
	"Common",
	"Debug",
	"Collections/PriorityList.cs",
	"SystemExtensions/CharExtensions.cs",
	"SystemExtensions/MemberInfoExtensions.cs",
	"SystemExtensions/StringExtensions.cs",
	"SystemExtensions/TypeExtensions.cs",
	"SystemExtensions/ListExtensions.cs",
	"SystemExtensions/EnumerableExtensions.cs",
	"Utils/ReflectUtil.cs",
]

# 同时时忽略的路径
ignore_paths = [
    'bin',
    'obj',
]