# 源目录
source = "../Decoherence/src"

# 目标目录
destiny = "src/Decoherence"

# 要同步的路径
sync_paths = [
    "Misc",
	"SystemExtensions/CharExtensions.cs",
	"SystemExtensions/DictionaryExtensions.cs",
	"SystemExtensions/StringExtensions.cs",
	"Utils/ReflectUtils.cs",
]

# 同时时忽略的路径
ignore_paths = [
    'bin',
    'obj',
]